<<<<<<< HEAD
create table Funcionario (
    Cod_Funcionario int not null,
    Nome varchar(50) not null,
    CPF varchar(15) not null,
    Sexo char(2) not null,
    Nome_Responsavel varchar(50) not null,
    Nacionalidade varchar(20) not null,
    Escolaridade varchar(40),
    Telefone varchar(20) not null,
    RG varchar(15) not null,
    Data_Nascimento date not null,
    Data_Efetivacao date not null,
    CEP varchar(20) not null,
    UF char(2) not null,
    Cidade varchar(30) not null,
    Bairro varchar(30) not null,
    Rua varchar(40) not null,
    Num_Residencia int not null,
    Usuario varchar(20) not null,
    Senha varchar(20) not null,
    Cargo varchar(20) not null,
	Foto_Funcionario longblob,
=======
create table funcionario (
	id_funcionario int not null,
    nome varchar (50) not null,
    cpf varchar(15) not null,
    sexo char (2) not null,
    nome_responsavel varchar(50),
    nacionalidade varchar(20) not null,
    escolaridade varchar(40),
    telefone varchar(20) not null,
    rg varchar(15) not null,
    data_nascimento date not null,
    data_efetivacao date not null,
    cep varchar(20) not null,
    uf char(2) not null,
    cidade varchar(30) not null,
    bairro varchar(30) not null,
    rua varchar(40) not null,
    num_residencia int not null,
    usuario varchar(20) not null,
    senha varchar(20) not null,
    cargo varchar(20) not null,
>>>>>>> 02cdef53f81af802bedbcf85b5dd4e9a07859808
    
    constraint pk_funcionario primary key (id_funcionario)
);
    